# Playbook que comprueba si las instancias de AWS están o no activas.

# Modificamos el filtro de instancia con nuestro correo:

- hosts: tag_instance_filter_three_tier_app_v_a_gonzalez_lopez_accenture_com
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
        
