# Playbook que comprueba si las instancias de AWS están o no activas.

# Modificamos el filtro de instancia con nuestro correo:

- hosts: tag:instance_filter=three-tier-app-v.a.gonzalez.lopez@accenture.com
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
        
