# Playbook to setup workstation and create osp network, router, SG and ssh keypair.
# Creamos el Inventario de la Workstation.
# Componentes de OpenStack.

# Llama al role:
# - setup-workstation:
#	Create clouds.yml

# Importa el Playbook site-install-isolated-node.yml (Nodo Aislado).  

---

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 
