# Playbook to setup workstation and create osp network, router, SG and ssh keypair.

# Playbook que configura la workstation y crea la red OSP, el grupo de seguridad y el par de claves ssh.
# Llama al role setup-worstation 

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation


- hosts: workstation
  become: yes
  roles:
    # Configuración de la workstation: crea el fichero clouds.yml e instala los paquetes.
    - setup-workstation 

# Importa el siguiente playbook para instalar el nodo aislado.
# The isolated node helps you in provisioning OpenStack instances and deploying a three-tier application on RHOSP (Red Hat OpenStack Platform) instances. 
- import_playbook: site-install-isolated-node.yml 

