# Implementaci贸n de la APP a tres niveles. 

# Llamada a los siguientes roles:
# - osp-facts: 
#	Generate in memory inventory for OSP instances role.
#	Inventario osp.
# - base_config: 
#	Plantilla de repositorio a tres niveles (extension.repo). 
#	Setup yum repo and base packages role.
#	templates/open-three-tier-app.repo ([rhel-7-server...]).
# - lb-tier:
#	Install HA proxy role (tasks/main: haproxy.cfg.j2).
# - app-tier:
# 	Install APP Server role.
#	Aplicaci贸n agregadada a tres niveles.
#	Instalaci贸n Tomcat
#	Tomcat implementado Ansible (index.html.j2).
# - db-tier:
#	Install PostgreSQL Server for database role.
#	Aplicaci贸n agregada a tres niveles.

# (Template: 3tier app deployment on QA Env and 3 tier app on Prod).

---

- hosts: workstation
  gather_facts: true 
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
