# Playbook que implementa la APP a tres niveles.
# Configure your instance to use the organization's local yum repository. 
# [rhel-7-server ...]

- hosts: workstation
  gather_facts: true

  # Llamada al role osp-facts el cual genera el inventario para OSP (OpenStack).
  # Generate in memory inventory for OSP instances role.
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
