# Genera el flujo de trabajo (workflow) desde el playbook workflow.yml.
# CI = Continuous Integration (Integración Continua, fusión de todas las copias de trabajo de los desarrolladores).
# CD = Continuous Deployment (Despliegue Continuo, las funcionalidades de software se entregan con frecuencia a través de implementaciones automatizadas).

- name: Create CI CD Workflow
  command: |
    tower-cli workflow create -n {{workflow_template_name}} --organization {{org_name}}

- name: Create workflow schema 
  template:
    src: workflow.j2
    dest: /root/workflow.yml

- name: Create workflow using schema
  command: |
    tower-cli workflow schema {{workflow_template_name}} @/root/workflow.yml

