---

# Base-config: Plantilla de Repositorio a tres niveles.
# Habilita el repositorio (extension.repo).

# Setup yum repo and base packages role.
# tasks file for base-config

- name: enable repos
  template:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644
